### ISSUE TITLE
delivery setup fails if terminal does not support colors.

### ISSUE THREAD

**Issue by dreamnite** [chef/delivery-cli#40]
Our default mandated ssh program by default uses vt-100 as a terminal type, which does not support extended colors. (strict vt100 only supports 8 colors).

This results in the following traceback: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ColorOutOfRange', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ColorOutOfRange', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
```

Perhaps disable colors by default on terminals that don't support the full set?

**Comment by vasanth1411** [comment]
export TERM=xterm

This should probably fix this issue

**Comment by nandanhegde73** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
